[package]
name = "typehash"
version = "0.1.0"
edition = "2018"

[workspace]

[dependencies]
typehash-macro = { path = "derive-macro" }

[dev-dependencies]
trybuild = "1.0"
rustversion = "1.0"
walkdir = "2.3"